# Generated by Django 2.0.13 on 2019-07-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechapub', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechamax', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='DISPONIBLE', max_length=80)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('encuesta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.Encuesta')),
            ],
        ),
    ]
