# Generated by Django 2.0.13 on 2019-07-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_infprme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infprme',
            new_name='Informe',
        ),
    ]
