# Generated by Django 2.0.13 on 2019-07-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190711_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='foto',
            field=models.ImageField(default='photos/lol.png', upload_to='photos'),
        ),
    ]
