# Generated by Django 2.0.13 on 2019-07-11 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_realizara',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
