# Generated by Django 2.0.13 on 2019-07-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_evento_fecha_realizara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.CharField(max_length=200),
        ),
    ]
