# Generated by Django 2.0.13 on 2019-07-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190711_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='foto',
            field=models.CharField(max_length=200),
        ),
    ]
